sudo: false

language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..."

script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet .
  - go test -v -race -cover .
