name: 'Tests'

on:
  push:
    branches: ['master']
  pull_request: {}

jobs:
  test:
    name: 'Test with Go ${{ matrix.go }}'
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.9'
          - '1.10'
          - '1.11'
          - '1.12'
          - '1.13'
          - '1.14'
          - '1'

    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run fmt
        run: diff -u <(echo -n) <(gofmt -d -s .)

      - name: Run vet
        run: go vet .

      - name: Run tests
        run: go test -v -race -cover
